CREATE TABLE IF NOT EXISTS camps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive', 'archived')),
    coordination_channel TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS families (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id TEXT NOT NULL UNIQUE,
    family_head TEXT,
    household_address TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('manager', 'camp_operator', 'officer')),
    camp_id UUID REFERENCES camps(id) ON DELETE RESTRICT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id TEXT,
    family_id TEXT,
    family_uuid UUID REFERENCES families(id) ON DELETE SET NULL,
    camp_id UUID REFERENCES camps(id) ON DELETE RESTRICT,
    seed_key TEXT,
    full_name TEXT NOT NULL,
    alternate_name TEXT,
    age INTEGER CHECK (age IS NULL OR (age >= 0 AND age <= 120)),
    date_of_birth DATE,
    gender TEXT,
    family_head TEXT,
    relationship_to_head TEXT,
    father_or_guardian_name TEXT,
    mother_name TEXT,
    primary_language TEXT,
    house_number TEXT,
    street TEXT,
    area TEXT,
    village_or_town TEXT,
    district TEXT,
    state TEXT,
    postal_code TEXT,
    full_address TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone_demo TEXT,
    known_relative_name TEXT,
    known_relative_relationship TEXT,
    last_known_location TEXT,
    registered_camp TEXT,
    disaster_status TEXT,
    assistance_needed TEXT,
    registration_date DATE,
    record_source TEXT,
    identity_verification_status TEXT,
    notes TEXT,
    relative_name TEXT,
    camp_name TEXT NOT NULL,
    address TEXT,
    status TEXT NOT NULL DEFAULT 'registered'
        CHECK (status IN ('missing', 'survivor', 'registered')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE people ADD COLUMN IF NOT EXISTS person_id TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS family_id TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS family_uuid UUID REFERENCES families(id) ON DELETE SET NULL;
ALTER TABLE people ADD COLUMN IF NOT EXISTS camp_id UUID REFERENCES camps(id) ON DELETE RESTRICT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS seed_key TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS alternate_name TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE people ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE people ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS family_head TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS relationship_to_head TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS father_or_guardian_name TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS mother_name TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS primary_language TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS house_number TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS street TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS area TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS village_or_town TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS district TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS postal_code TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS full_address TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS emergency_contact_name TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS emergency_contact_phone_demo TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS known_relative_name TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS known_relative_relationship TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS last_known_location TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS registered_camp TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS disaster_status TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS assistance_needed TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS registration_date DATE;
ALTER TABLE people ADD COLUMN IF NOT EXISTS record_source TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS identity_verification_status TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS relative_name TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS camp_name TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'registered';
ALTER TABLE people ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

INSERT INTO camps (name)
SELECT DISTINCT COALESCE(NULLIF(registered_camp, ''), NULLIF(camp_name, ''))
FROM people
WHERE COALESCE(NULLIF(registered_camp, ''), NULLIF(camp_name, '')) IS NOT NULL
    AND COALESCE(NULLIF(registered_camp, ''), NULLIF(camp_name, '')) <> 'Not assigned'
ON CONFLICT (name) DO NOTHING;

UPDATE people AS person
SET camp_id = camp.id
FROM camps AS camp
WHERE person.camp_id IS NULL
    AND camp.name = COALESCE(NULLIF(person.registered_camp, ''), NULLIF(person.camp_name, ''));

INSERT INTO families (family_id, family_head, household_address)
SELECT family_id, MAX(family_head), MAX(COALESCE(NULLIF(full_address, ''), NULLIF(address, '')))
FROM people
WHERE NULLIF(family_id, '') IS NOT NULL
GROUP BY family_id
ON CONFLICT (family_id) DO UPDATE SET
        family_head = COALESCE(families.family_head, EXCLUDED.family_head),
        household_address = COALESCE(families.household_address, EXCLUDED.household_address);

UPDATE people AS person
SET family_uuid = family.id
FROM families AS family
WHERE person.family_uuid IS NULL AND family.family_id = person.family_id;

CREATE UNIQUE INDEX IF NOT EXISTS people_seed_key_unique
    ON people (seed_key);
CREATE UNIQUE INDEX IF NOT EXISTS people_person_id_unique
    ON people (person_id);
CREATE INDEX IF NOT EXISTS people_family_id_idx ON people (family_id);
CREATE INDEX IF NOT EXISTS people_camp_name_idx ON people (camp_name);
CREATE INDEX IF NOT EXISTS people_registered_camp_idx ON people (registered_camp);
CREATE INDEX IF NOT EXISTS people_address_idx ON people (address);
CREATE INDEX IF NOT EXISTS people_camp_id_idx ON people (camp_id);
CREATE INDEX IF NOT EXISTS people_family_uuid_idx ON people (family_uuid);

CREATE TABLE IF NOT EXISTS camp_records (
    id UUID PRIMARY KEY,
    camp_id UUID NOT NULL REFERENCES camps(id) ON DELETE RESTRICT,
    record_type TEXT NOT NULL CHECK (record_type IN ('missing', 'survivor')),
    person_id BIGINT REFERENCES people(id) ON DELETE SET NULL,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'registered',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS missing_reports (
    record_id UUID PRIMARY KEY REFERENCES camp_records(id) ON DELETE RESTRICT,
    camp_id UUID NOT NULL REFERENCES camps(id) ON DELETE RESTRICT,
    person_id BIGINT REFERENCES people(id) ON DELETE SET NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS survivor_registrations (
    record_id UUID PRIMARY KEY REFERENCES camp_records(id) ON DELETE RESTRICT,
    camp_id UUID NOT NULL REFERENCES camps(id) ON DELETE RESTRICT,
    person_id BIGINT REFERENCES people(id) ON DELETE SET NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_events (
    event_id UUID PRIMARY KEY,
    camp_id UUID NOT NULL REFERENCES camps(id) ON DELETE RESTRICT,
    event_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'synced', 'failed')),
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    synced_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS candidate_matches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
    candidate_person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
    clue_scores JSONB NOT NULL,
    combined_score NUMERIC(5, 2) NOT NULL CHECK (combined_score BETWEEN 0 AND 100),
    explanation JSONB,
    explanation_ready BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'candidate_found'
        CHECK (status IN ('candidate_found', 'verified', 'approved', 'rejected', 'follow_up')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_person_id, candidate_person_id),
    CHECK (source_person_id <> candidate_person_id)
);

CREATE TABLE IF NOT EXISTS verification_reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    candidate_match_id UUID NOT NULL REFERENCES candidate_matches(id) ON DELETE RESTRICT,
    reviewer_id UUID REFERENCES staff_users(id) ON DELETE SET NULL,
    reviewer_username TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('evidence_recorded', 'approved', 'rejected', 'follow_up')),
    evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    camp_id UUID NOT NULL REFERENCES camps(id) ON DELETE RESTRICT,
    candidate_match_id UUID NOT NULL REFERENCES candidate_matches(id) ON DELETE RESTRICT,
    recipient_id UUID REFERENCES staff_users(id) ON DELETE RESTRICT,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'delivered', 'read')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    UNIQUE (camp_id, candidate_match_id, recipient_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS notifications_camp_match_null_recipient_unique
    ON notifications (camp_id, candidate_match_id) WHERE recipient_id IS NULL;

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id UUID REFERENCES staff_users(id) ON DELETE SET NULL,
    actor_username TEXT NOT NULL,
    action TEXT NOT NULL,
    object_type TEXT NOT NULL,
    object_id TEXT,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS camps_status_idx ON camps (status);
CREATE INDEX IF NOT EXISTS camp_records_camp_id_idx ON camp_records (camp_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sync_events_camp_status_idx ON sync_events (camp_id, status);
CREATE INDEX IF NOT EXISTS candidate_matches_status_idx ON candidate_matches (status);
CREATE INDEX IF NOT EXISTS notifications_camp_status_idx ON notifications (camp_id, status);

CREATE TABLE IF NOT EXISTS match_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
    candidate_id BIGINT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
    officer_username TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('reviewed', 'follow_up', 'not_a_match')),
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (person_id <> candidate_id)
);

ALTER TABLE candidate_matches ADD COLUMN IF NOT EXISTS explanation JSONB;
ALTER TABLE candidate_matches ADD COLUMN IF NOT EXISTS explanation_ready BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE candidate_matches ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS reunification_cases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    missing_person_id BIGINT NOT NULL UNIQUE REFERENCES people(id) ON DELETE RESTRICT,
    status TEXT NOT NULL DEFAULT 'OPEN'
        CHECK (status IN ('OPEN', 'POTENTIAL_MATCH', 'UNDER_VERIFICATION', 'VERIFIED', 'REUNIFICATION_PENDING', 'REUNITED', 'CLOSED')),
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
    closed_at TIMESTAMPTZ,
    closed_by UUID REFERENCES staff_users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((status = 'CLOSED') = (closed_at IS NOT NULL))
);

INSERT INTO reunification_cases (missing_person_id)
SELECT id FROM people WHERE status = 'missing'
ON CONFLICT (missing_person_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS reunification_events (
    event_id UUID PRIMARY KEY,
    case_id UUID NOT NULL REFERENCES reunification_cases(id) ON DELETE RESTRICT,
    candidate_match_id UUID REFERENCES candidate_matches(id) ON DELETE RESTRICT,
    action TEXT NOT NULL CHECK (action IN ('reunion_confirmed', 'case_reopened')),
    actor_id UUID REFERENCES staff_users(id) ON DELETE SET NULL,
    actor_username TEXT NOT NULL,
    evidence JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS case_sync_outbox (
    event_id UUID NOT NULL REFERENCES reunification_events(event_id) ON DELETE RESTRICT,
    camp_id UUID NOT NULL REFERENCES camps(id) ON DELETE RESTRICT,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'delivered')),
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMPTZ,
    PRIMARY KEY (event_id, camp_id)
);

CREATE TABLE IF NOT EXISTS person_photos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,
    storage_key TEXT NOT NULL UNIQUE,
    mime_type TEXT NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp')),
    sha256 TEXT NOT NULL,
    byte_size INTEGER NOT NULL CHECK (byte_size > 0),
    width INTEGER NOT NULL CHECK (width > 0),
    height INTEGER NOT NULL CHECK (height > 0),
    created_by UUID REFERENCES staff_users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retained BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE person_photos ADD COLUMN IF NOT EXISTS camp_id UUID REFERENCES camps(id) ON DELETE RESTRICT;
ALTER TABLE person_photos ADD COLUMN IF NOT EXISTS original_filename TEXT NOT NULL DEFAULT 'previously uploaded image';
ALTER TABLE person_photos ADD COLUMN IF NOT EXISTS normalized_sha256 TEXT;
ALTER TABLE person_photos ADD COLUMN IF NOT EXISTS perceptual_hash TEXT;
ALTER TABLE person_photos ADD COLUMN IF NOT EXISTS access_policy TEXT NOT NULL DEFAULT 'role_and_camp';
ALTER TABLE person_photos ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;

UPDATE person_photos AS photo
SET camp_id = people.camp_id
FROM people
WHERE photo.person_id = people.id AND photo.camp_id IS NULL;

CREATE TABLE IF NOT EXISTS photo_descriptions (
    photo_id UUID PRIMARY KEY REFERENCES person_photos(id) ON DELETE RESTRICT,
    description JSONB NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('ollama', 'officer')),
    model_name TEXT,
    review_status TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'reviewed', 'corrected')),
    analyzed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by UUID REFERENCES staff_users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS photo_ai_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    photo_id UUID NOT NULL REFERENCES person_photos(id) ON DELETE RESTRICT,
    status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'processing', 'retry_wait', 'completed', 'failed', 'cancelled')),
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS reunification_cases_status_idx ON reunification_cases (status, updated_at DESC);
CREATE INDEX IF NOT EXISTS reunification_events_case_idx ON reunification_events (case_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS case_sync_outbox_pending_idx ON case_sync_outbox (camp_id, status, created_at);
CREATE INDEX IF NOT EXISTS candidate_matches_active_status_idx ON candidate_matches (is_active, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS person_photos_person_idx ON person_photos (person_id, created_at DESC);
CREATE INDEX IF NOT EXISTS person_photos_sha256_idx ON person_photos (sha256) WHERE retained = TRUE;
CREATE INDEX IF NOT EXISTS person_photos_normalized_hash_idx ON person_photos (normalized_sha256) WHERE retained = TRUE;
CREATE INDEX IF NOT EXISTS person_photos_camp_idx ON person_photos (camp_id, created_at DESC) WHERE retained = TRUE;
CREATE INDEX IF NOT EXISTS photo_ai_jobs_work_idx ON photo_ai_jobs (status, next_attempt_at, created_at);